language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm test
  - npm run webdriver-update
  - npm run webdriver-start
  - npm run protractor