language: node_js
node_js:
  - "8"
# Cache node_modules
cache:
  directories:
    - "node_modules"
install:
  - npm install -g protractor

before_script:
  - webdriver-manager update --versions.chrome 83
  - webdriver-manager start &
  - sleep 3

script:
  - protractor headless_config.js