version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: - webdriver-manager update --versions.chrome=73.0.3683.86 &
                   - webdriver-manager start --versions.chrome=73.0.3683.86 &
                   - sleep 3
            - run: npm install -g protractor
            - run: protractor headless_config.js
workflows:
    build-and-test:
      jobs:
        - build-and-test